Repository DanishAbdullahPy/Html-for-freshmans, pull requests merged in 2023-10, with the labels that each got.

#10 Create asharfulkhan.html
  asharfulkhan.html
Labels: enhancement, hacktoberfest2023, hacktoberfestaccepted

#37 Create index2.html
  index2.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#36 Create ken.html
  ken.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#34 Create Mohammad Hamzah Karim2.html
  Mohammad Hamzah Karim.html
Labels: hacktoberfest2023, hacktoberfestaccepted

#33 Create imad2.html
  imad2.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#32 Create zubiya.html
  zubiya.html
Labels: hacktoberfest2023, hacktoberfestaccepted

#30 Create Md Faizan.html
  Md Faizan.html
Labels: hacktoberfest2023, hacktoberfestaccepted

#29 Create Shaad.html
  Shaad.html
Labels: hacktoberfest2023, hacktoberfestaccepted

#28 Create Omar.html
  Omar.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#39 Add my HTML contribution
  aditya.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#38 Create dxeon.html
  dxeon.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#26 Create Arshad.html
  Arshad.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#25 Create MaseeraFatima.html
  MaseeraFatima.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#24 Create Saad.html
  Saad.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#23 Create Suhail.html
  Suhail.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#22 Create nida.html
  nida.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#21 Create shammy.html
  shammy.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#20 Create zama.html
  zama.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#19 Create Arsalan.html
  Arsalan.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#18 Create anas.html
  anas.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#17 Create Haris.html
  Haris.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#16 Create Hunra.html
  Hunra.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#15 Create taaha.html
  taaha.html
Labels: good first issue, hacktoberfest2023, hacktoberfestaccepted

#14 Create aasif.html
  aasif.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#13 zishan.html
  zishan.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#12 Create ary.html
  ary.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#11 Create Ashraf.html
  Ashraf.html
Labels: good first issue, hacktoberfest2023, hacktoberfestaccepted

#8 Create Ayesha.html
  Ayesha.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#7 Added Nav Bar in Index.html
  index.html
  style.css
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#6 Create website.html
  website.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#4 Responsive Table Added
  Responsive Table.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#3 Creative-table-added
  Modern Table.html
Labels: help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#42 Create Shail.html
  Shail.html
Labels: hacktoberfest2023, hacktoberfestaccepted

#51 Revert "webpage card"
  Webpage card/images/Adnan.jpg
  Webpage card/images/Background2.jpg
  Webpage card/images/arrow.png
  Webpage card/images/background.png
  Webpage card/images/dribble.png
  Webpage card/images/instagram.png
  Webpage card/images/menu.png
  Webpage card/images/setting.png
  Webpage card/images/telegram.png
  Webpage card/index.html
  Webpage card/style.css
Labels: documentation, help wanted, good first issue, hacktoberfest2023, hacktoberfestaccepted

#50 Create adeel.html
  adeel.html
Labels: documentation, hacktoberfest2023, hacktoberfestaccepted

#49 Create nikhil.html
  nikhil.html
Labels: hacktoberfest2023, hacktoberfestaccepted

#52 New html file for alert
  Mayank.html
Labels: good first issue, hacktoberfest2023, hacktoberfestaccepted

#55 Added html code
  saanvi.html
Labels: help wanted, hacktoberfest2023, hacktoberfestaccepted

#54 Create Table.html
  Table.html
Labels: good first issue, hacktoberfest2023, hacktoberfestaccepted

#45 srujana.html
  srujana.html
Labels: hacktoberfest2023, hacktoberfestaccepted

#46 new.html
  new.html
Labels: hacktoberfest2023, hacktoberfestaccepted

#43 Om.html
  Om.html
Labels: hacktoberfest2023, hacktoberfestaccepted

#57 Create Sumith.html
  Sumith.html
Labels: hacktoberfest2023, hacktoberfestaccepted
